logging:
  level:
    com.serengeti.hyu.backend: DEBUG
spring:
  profiles:
    include: secret
  output:
    ansi:
      enabled: always
  config:
    import: classpath:application-secret.yml
  datasource:
    url: jdbc:mysql://localhost:3306/hue
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
